// Generated by CoffeeScript 1.7.1
var ttt;

ttt = ttt || {};

ttt.tttApp = angular.module("tttApp", []);

ttt.TicTacToeController = function($scope) {
  var win_combos;
  win_combos = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];
  $scope.players = [
    {
      name: "Ernie",
      marker: "X",
      img_url: "img/ernie.jpg"
    }, {
      name: "Bert",
      marker: "O",
      img_url: "img/bert.jpg"
    }
  ];
  $scope.tiles = [
    {
      id: 0,
      active: false,
      marker: ""
    }, {
      id: 1,
      active: false,
      marker: ""
    }, {
      id: 2,
      active: false,
      marker: ""
    }, {
      id: 3,
      active: false,
      marker: ""
    }, {
      id: 4,
      active: false,
      marker: ""
    }, {
      id: 5,
      active: false,
      marker: ""
    }, {
      id: 6,
      active: false,
      marker: ""
    }, {
      id: 7,
      active: false,
      marker: ""
    }, {
      id: 8,
      active: false,
      marker: ""
    }
  ];
  $scope.turns = 0;
  $scope.currentPlayer = _.first($scope.players);
  $scope.handleClick = function(tile) {
    if (tile.active) {
      return;
    }
    tile.active = true;
    $scope.turns++;
    tile.marker = $scope.currentPlayer.marker;
    if ($scope.isWin()) {
      return $scope.theEnd = {
        message: $scope.currentPlayer.name + " won the game!",
        img_url: $scope.currentPlayer.img_url
      };
    } else if ($scope.isTie()) {
      return $scope.theEnd = {
        message: "It's a tie!",
        img_url: "img/rubberduckie.jpg"
      };
    } else {
      return $scope.currentPlayer = $scope.players[$scope.turns % 2];
    }
  };
  $scope.isTie = function() {
    return $scope.turns === $scope.tiles.length;
  };
  $scope.isWin = function() {
    var currentPlayerBoardData, matchFound;
    currentPlayerBoardData = [];
    _.each($scope.tiles, function(tile, i) {
      if (tile.marker === $scope.currentPlayer.marker) {
        return currentPlayerBoardData.push(i);
      }
    });
    matchFound = false;
    _.each(win_combos, function(combo) {
      if (_.intersection(combo, currentPlayerBoardData).length === combo.length) {
        return matchFound = true;
      }
    });
    return matchFound;
  };
  return $scope.playAgain = function() {
    return window.location.href = window.location.href;
  };
};

ttt.tttApp.controller('ttt.TicTacToeController', ttt.TicTacToeController);
